#!/bin/bash

# openshift_gears_present - Munin plugin for charting gears
# active/idle on OpenShift Node instances
#
# Copyright © 2013, Tim Bielawa <tbielawa@redhat.com>
# Copyright © 2013, Red Hat, Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.


OPENSHIFT_VOLUME=/var/lib/openshift

config()
{
cat <<EOF
graph_title OpenShift Gears Present/Idle
graph_vlabel Gears
graph_category OpenShift
graph_scale no
graph_info OpenShift gears present/idle on this node instance
gears_present.label Gears Present
gears_idle.label Gears idle
EOF
}

gears_present()
{
    oo-admin-ctl-gears list | wc -l
}

gears_idle()
{
    oo-admin-ctl-gears listidle | wc -l
}

run()
{
    echo "gears_present.value `gears_present`"
    echo -n "gears_idle.value `gears_idle`"
}

case $1 in
    config)
	config
	exit 0;
	;;
    *)
	run
	exit 0;
	;;
esac
